/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.62
 * Generated at: 2015-06-28 18:30:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.web;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class demo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("    <title>Bootstrap Slider Component Carousel/Slideshow/Gallery/Banner</title>\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap core CSS -->\r\n");
      out.write("    <link href=\"../css/bootstrap.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css\">\r\n");
      out.write("    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->\r\n");
      out.write("    <!--[if lt IE 9]>\r\n");
      out.write("      <script src=\"https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js\"></script>\r\n");
      out.write("      <script src=\"https://oss.maxcdn.com/respond/1.4.2/respond.min.js\"></script>\r\n");
      out.write("    <![endif]-->\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div id=\"slider1_container\" style=\"display: none; position: relative; margin: 0 auto; width: 1140px; height: 442px; overflow: hidden;\">\r\n");
      out.write("\r\n");
      out.write("            <!-- Loading Screen -->\r\n");
      out.write("            <div u=\"loading\" style=\"position: absolute; top: 0px; left: 0px;\">\r\n");
      out.write("                <div style=\"filter: alpha(opacity=70); opacity:0.7; position: absolute; display: block;\r\n");
      out.write("\r\n");
      out.write("                background-color: #000; top: 0px; left: 0px;width: 100%; height:100%;\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div style=\"position: absolute; display: block; background: url(../img/loading.gif) no-repeat center center;\r\n");
      out.write("\r\n");
      out.write("                top: 0px; left: 0px;width: 100%;height:100%;\">\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Slides Container -->\r\n");
      out.write("            <div u=\"slides\" style=\"cursor: move; position: absolute; left: 0px; top: 0px; width: 1140px; height: 442px;\r\n");
      out.write("            overflow: hidden;\">\r\n");
      out.write("                <div>\r\n");
      out.write("                    <img u=\"image\" src2=\"../File/01.jpg\" />\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <img u=\"image\" src2=\"../File/02.jpg\" />\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <img u=\"image\" src2=\"../File/03.jpg\" />\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <img u=\"image\" src2=\"../File/04.jpg\" />\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <style>\r\n");
      out.write("                /* jssor slider bullet navigator skin 05 css */\r\n");
      out.write("                /*\r\n");
      out.write("                .jssorb05 div           (normal)\r\n");
      out.write("                .jssorb05 div:hover     (normal mouseover)\r\n");
      out.write("                .jssorb05 .av           (active)\r\n");
      out.write("                .jssorb05 .av:hover     (active mouseover)\r\n");
      out.write("                .jssorb05 .dn           (mousedown)\r\n");
      out.write("                */\r\n");
      out.write("                .jssorb05 {\r\n");
      out.write("                    position: absolute;\r\n");
      out.write("                }\r\n");
      out.write("                .jssorb05 div, .jssorb05 div:hover, .jssorb05 .av {\r\n");
      out.write("                    position: absolute;\r\n");
      out.write("                    /* size of bullet elment */\r\n");
      out.write("                    width: 16px;\r\n");
      out.write("                    height: 16px;\r\n");
      out.write("                    background: url(../img/b05.png) no-repeat;\r\n");
      out.write("                    overflow: hidden;\r\n");
      out.write("                    cursor: pointer;\r\n");
      out.write("                }\r\n");
      out.write("                .jssorb05 div { background-position: -7px -7px; }\r\n");
      out.write("                .jssorb05 div:hover, .jssorb05 .av:hover { background-position: -37px -7px; }\r\n");
      out.write("                .jssorb05 .av { background-position: -67px -7px; }\r\n");
      out.write("                .jssorb05 .dn, .jssorb05 .dn:hover { background-position: -97px -7px; }\r\n");
      out.write("            </style>\r\n");
      out.write("            <!-- bullet navigator container -->\r\n");
      out.write("            <div u=\"navigator\" class=\"jssorb05\" style=\"bottom: 16px; right: 6px;\">\r\n");
      out.write("                <!-- bullet navigator item prototype -->\r\n");
      out.write("                <div u=\"prototype\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!--#endregion Bullet Navigator Skin End -->\r\n");
      out.write("            \r\n");
      out.write("            <!--#region Arrow Navigator Skin Begin -->\r\n");
      out.write("            <!-- Help: http://www.jssor.com/development/slider-with-arrow-navigator-jquery.html -->\r\n");
      out.write("            <style>\r\n");
      out.write("                /* jssor slider arrow navigator skin 11 css */\r\n");
      out.write("                /*\r\n");
      out.write("                .jssora11l                  (normal)\r\n");
      out.write("                .jssora11r                  (normal)\r\n");
      out.write("                .jssora11l:hover            (normal mouseover)\r\n");
      out.write("                .jssora11r:hover            (normal mouseover)\r\n");
      out.write("                .jssora11l.jssora11ldn      (mousedown)\r\n");
      out.write("                .jssora11r.jssora11rdn      (mousedown)\r\n");
      out.write("                */\r\n");
      out.write("                .jssora11l, .jssora11r {\r\n");
      out.write("                    display: block;\r\n");
      out.write("                    position: absolute;\r\n");
      out.write("                    /* size of arrow element */\r\n");
      out.write("                    width: 37px;\r\n");
      out.write("                    height: 37px;\r\n");
      out.write("                    cursor: pointer;\r\n");
      out.write("                    background: url(../img/a11.png) no-repeat;\r\n");
      out.write("                    overflow: hidden;\r\n");
      out.write("                }\r\n");
      out.write("                .jssora11l { background-position: -11px -41px; }\r\n");
      out.write("                .jssora11r { background-position: -71px -41px; }\r\n");
      out.write("                .jssora11l:hover { background-position: -131px -41px; }\r\n");
      out.write("                .jssora11r:hover { background-position: -191px -41px; }\r\n");
      out.write("                .jssora11l.jssora11ldn { background-position: -251px -41px; }\r\n");
      out.write("                .jssora11r.jssora11rdn { background-position: -311px -41px; }\r\n");
      out.write("            </style>\r\n");
      out.write("            <!-- Arrow Left -->\r\n");
      out.write("            <span u=\"arrowleft\" class=\"jssora11l\" style=\"top: 123px; left: 8px;\">\r\n");
      out.write("            </span>\r\n");
      out.write("            <!-- Arrow Right -->\r\n");
      out.write("            <span u=\"arrowright\" class=\"jssora11r\" style=\"top: 123px; right: 8px;\">\r\n");
      out.write("            </span>\r\n");
      out.write("            <!--#endregion Arrow Navigator Skin End -->\r\n");
      out.write("            <a style=\"display: none\" href=\"http://www.jssor.com\">Bootstrap Slider</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Jssor Slider End -->\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"../js/jquery-1.9.1.min.js\"></script>\r\n");
      out.write("    <script src=\"../js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"../js/docs.min.js\"></script>\r\n");
      out.write("    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->\r\n");
      out.write("    <script src=\"../js/ie10-viewport-bug-workaround.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"../js/jssor.slider.mini.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <script>\r\n");
      out.write("\r\n");
      out.write("        jQuery(document).ready(function ($) {\r\n");
      out.write("            var options = {\r\n");
      out.write("                $AutoPlay: true,                                    //[Optional] Whether to auto play, to enable slideshow, this option must be set to true, default value is false\r\n");
      out.write("                $AutoPlaySteps: 1,                                  //[Optional] Steps to go for each navigation request (this options applys only when slideshow disabled), the default value is 1\r\n");
      out.write("                $AutoPlayInterval: 2000,                            //[Optional] Interval (in milliseconds) to go for next slide since the previous stopped if the slider is auto playing, default value is 3000\r\n");
      out.write("                $PauseOnHover: 1,                                   //[Optional] Whether to pause when mouse over if a slider is auto playing, 0 no pause, 1 pause for desktop, 2 pause for touch device, 3 pause for desktop and touch device, 4 freeze for desktop, 8 freeze for touch device, 12 freeze for desktop and touch device, default value is 1\r\n");
      out.write("\r\n");
      out.write("                $ArrowKeyNavigation: true,   \t\t\t            //[Optional] Allows keyboard (arrow key) navigation or not, default value is false\r\n");
      out.write("                $SlideEasing: $JssorEasing$.$EaseOutQuint,          //[Optional] Specifies easing for right to left animation, default value is $JssorEasing$.$EaseOutQuad\r\n");
      out.write("                $SlideDuration: 800,                                //[Optional] Specifies default duration (swipe) for slide in milliseconds, default value is 500\r\n");
      out.write("                $MinDragOffsetToSlide: 20,                          //[Optional] Minimum drag offset to trigger slide , default value is 20\r\n");
      out.write("                //$SlideWidth: 600,                                 //[Optional] Width of every slide in pixels, default value is width of 'slides' container\r\n");
      out.write("                //$SlideHeight: 300,                                //[Optional] Height of every slide in pixels, default value is height of 'slides' container\r\n");
      out.write("                $SlideSpacing: 0, \t\t\t\t\t                //[Optional] Space between each slide in pixels, default value is 0\r\n");
      out.write("                $DisplayPieces: 1,                                  //[Optional] Number of pieces to display (the slideshow would be disabled if the value is set to greater than 1), the default value is 1\r\n");
      out.write("                $ParkingPosition: 0,                                //[Optional] The offset position to park slide (this options applys only when slideshow disabled), default value is 0.\r\n");
      out.write("                $UISearchMode: 1,                                   //[Optional] The way (0 parellel, 1 recursive, default value is 1) to search UI components (slides container, loading screen, navigator container, arrow navigator container, thumbnail navigator container etc).\r\n");
      out.write("                $PlayOrientation: 1,                                //[Optional] Orientation to play slide (for auto play, navigation), 1 horizental, 2 vertical, 5 horizental reverse, 6 vertical reverse, default value is 1\r\n");
      out.write("                $DragOrientation: 1,                                //[Optional] Orientation to drag slide, 0 no drag, 1 horizental, 2 vertical, 3 either, default value is 1 (Note that the $DragOrientation should be the same as $PlayOrientation when $DisplayPieces is greater than 1, or parking position is not 0)\r\n");
      out.write("\r\n");
      out.write("                $ArrowNavigatorOptions: {                           //[Optional] Options to specify and enable arrow navigator or not\r\n");
      out.write("                    $Class: $JssorArrowNavigator$,                  //[Requried] Class to create arrow navigator instance\r\n");
      out.write("                    $ChanceToShow: 2,                               //[Required] 0 Never, 1 Mouse Over, 2 Always\r\n");
      out.write("                    $AutoCenter: 2,                                 //[Optional] Auto center arrows in parent container, 0 No, 1 Horizontal, 2 Vertical, 3 Both, default value is 0\r\n");
      out.write("                    $Steps: 1,                                      //[Optional] Steps to go for each navigation request, default value is 1\r\n");
      out.write("                    $Scale: false                                   //Scales bullets navigator or not while slider scale\r\n");
      out.write("                },\r\n");
      out.write("\r\n");
      out.write("                $BulletNavigatorOptions: {                                //[Optional] Options to specify and enable navigator or not\r\n");
      out.write("                    $Class: $JssorBulletNavigator$,                       //[Required] Class to create navigator instance\r\n");
      out.write("                    $ChanceToShow: 2,                               //[Required] 0 Never, 1 Mouse Over, 2 Always\r\n");
      out.write("                    $AutoCenter: 1,                                 //[Optional] Auto center navigator in parent container, 0 None, 1 Horizontal, 2 Vertical, 3 Both, default value is 0\r\n");
      out.write("                    $Steps: 1,                                      //[Optional] Steps to go for each navigation request, default value is 1\r\n");
      out.write("                    $Lanes: 1,                                      //[Optional] Specify lanes to arrange items, default value is 1\r\n");
      out.write("                    $SpacingX: 12,                                   //[Optional] Horizontal space between each item in pixel, default value is 0\r\n");
      out.write("                    $SpacingY: 4,                                   //[Optional] Vertical space between each item in pixel, default value is 0\r\n");
      out.write("                    $Orientation: 1,                                //[Optional] The orientation of the navigator, 1 horizontal, 2 vertical, default value is 1\r\n");
      out.write("                    $Scale: false                                   //Scales bullets navigator or not while slider scale\r\n");
      out.write("                }\r\n");
      out.write("            };\r\n");
      out.write("\r\n");
      out.write("            //Make the element 'slider1_container' visible before initialize jssor slider.\r\n");
      out.write("            $(\"#slider1_container\").css(\"display\", \"block\");\r\n");
      out.write("            var jssor_slider1 = new $JssorSlider$(\"slider1_container\", options);\r\n");
      out.write("\r\n");
      out.write("            //responsive code begin\r\n");
      out.write("            //you can remove responsive code if you don't want the slider scales while window resizes\r\n");
      out.write("            function ScaleSlider() {\r\n");
      out.write("                var parentWidth = jssor_slider1.$Elmt.parentNode.clientWidth;\r\n");
      out.write("                if (parentWidth) {\r\n");
      out.write("                    jssor_slider1.$ScaleWidth(parentWidth - 30);\r\n");
      out.write("                }\r\n");
      out.write("                else\r\n");
      out.write("                    window.setTimeout(ScaleSlider, 30);\r\n");
      out.write("            }\r\n");
      out.write("            ScaleSlider();\r\n");
      out.write("\r\n");
      out.write("            $(window).bind(\"load\", ScaleSlider);\r\n");
      out.write("            $(window).bind(\"resize\", ScaleSlider);\r\n");
      out.write("            $(window).bind(\"orientationchange\", ScaleSlider);\r\n");
      out.write("            //responsive code end\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
