/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.62
 * Generated at: 2015-06-30 18:11:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.web;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class imgviewer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t<meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("    <title>Images Viewer</title>\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap core CSS -->\r\n");
      out.write("    <link href=\"../css/bootstrap.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css\">\r\n");
      out.write("\t\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\r\n");
      out.write("\t\tfunction initSlider(){\r\n");
      out.write("\t\t\tvar div = document.createElement('div');\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<style type=\"text/css\">\r\n");
      out.write("\t\th1 {\r\n");
      out.write("\t\t\tfont-family: cursive;\r\n");
      out.write("\t\t\tfont-variant: small-caps;\r\n");
      out.write("\t\t\tfont-size: 50px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tbody{\r\n");
      out.write("\t\t\tmargin: 0;\r\n");
      out.write("\t\t\tbackground-color: rgba(6, 255, 0, 0.34);\r\n");
      out.write("\t\t\tbackground-image: linear-gradient(to left, rgba(74, 255, 0, 1) 0%, rgba(8, 66, 16, 1) 98%);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.container{\r\n");
      out.write("\t\t\ttext-align: center;\r\n");
      out.write("\t\t\tmargin: 1%;\r\n");
      out.write("\t\t\tpadding: 5%;\r\n");
      out.write("\t\t\tbackground-color: rgb(127, 147, 147);\r\n");
      out.write("\t\t\theight: auto;\r\n");
      out.write("\t\t\tmin-height: 100%;\r\n");
      out.write("\t\t\twidth: auto;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.btn {\r\n");
      out.write("\t\t\tmargin-top: 50px;\r\n");
      out.write("\t\t\tborder-radius: 25px;\r\n");
      out.write("\t\t\tpadding: 5px 20px;\r\n");
      out.write("\t\t\tbackground-color: lime;\r\n");
      out.write("\t\t\tcursor: pointer;\r\n");
      out.write("\t\t\tborder: 0px;\r\n");
      out.write("\t\t\tcolor: rgb(86, 86, 86);\r\n");
      out.write("\t\t\ttransition: background-color 0.2s ease-in-out;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.btn:hover {\r\n");
      out.write("\t\t\tbackground-color: rgba(0, 255, 0, 0.30);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#slider1_container{\r\n");
      out.write("\t\t\tdisplay: none;\r\n");
      out.write("\t\t\tposition: relative;\r\n");
      out.write("\t\t\tmargin: 0;\r\n");
      out.write("\t\t\tmargin-top: 50px;\r\n");
      out.write("\t\t\twidth: 100%!important;\r\n");
      out.write("\t\t\tmax-height: 500px!important;\r\n");
      out.write("\t\t\theight: 442px;\r\n");
      out.write("\t\t\toverflow: hidden;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</style>\r\n");
      out.write("\t</head>\r\n");
      out.write("\t\t<body>\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<h1>Images Viewer</h1>\r\n");
      out.write("\t\t\t\t<div id=\"slider1_container\">\r\n");
      out.write("\t\t            <!-- Loading Screen -->\r\n");
      out.write("\t\t            <div u=\"loading\" style=\"position: absolute; top: 0px; left: 0px;\">\r\n");
      out.write("\t\t                <div style=\"filter: alpha(opacity=70); opacity:0.7; position: absolute; display: block;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t                background-color: #000; top: 0px; left: 0px;width: 100%; height:100%;\">\r\n");
      out.write("\t\t                </div>\r\n");
      out.write("\t\t                <div style=\"position: absolute; display: block; background: url(../img/loading.gif) no-repeat center center;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t                top: 0px; left: 0px;width: 100%;height:100%;\">\r\n");
      out.write("\t\t                </div>\r\n");
      out.write("\t\t            </div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t            <!-- Slides Container -->\r\n");
      out.write("\t\t            <div u=\"slides\" id=\"slides\" style=\"cursor: move; position: absolute; left: 0px; top: 0px; width: 1140px; height: 442px;\r\n");
      out.write("\t\t            overflow: hidden;\">\r\n");
      out.write("\t\t                <div>\r\n");
      out.write("\t\t                    <img u=\"image\" src2=\"../File/01.jpg\" />\r\n");
      out.write("\t\t                </div>\r\n");
      out.write("\t\t                <div>\r\n");
      out.write("\t\t                    <img u=\"image\" src2=\"../File/02.jpg\" />\r\n");
      out.write("\t\t                </div>\r\n");
      out.write("\t\t                <div>\r\n");
      out.write("\t\t                    <img u=\"image\" src2=\"../File/03.jpg\" />\r\n");
      out.write("\t\t                </div>\r\n");
      out.write("\t\t                <div>\r\n");
      out.write("\t\t                    <img u=\"image\" src2=\"../File/04.jpg\" />\r\n");
      out.write("\t\t                </div>\r\n");
      out.write("\t\t            </div>\r\n");
      out.write("\t\t            \r\n");
      out.write("\t\t            <style>\r\n");
      out.write("\t\t                \r\n");
      out.write("\t\t                .jssorb05 {\r\n");
      out.write("\t\t                    position: absolute;\r\n");
      out.write("\t\t                }\r\n");
      out.write("\t\t                .jssorb05 div, .jssorb05 div:hover, .jssorb05 .av {\r\n");
      out.write("\t\t                    position: absolute;\r\n");
      out.write("\t\t                    width: 16px;\r\n");
      out.write("\t\t                    height: 16px;\r\n");
      out.write("\t\t                    background: url(../img/b05.png) no-repeat;\r\n");
      out.write("\t\t                    overflow: hidden;\r\n");
      out.write("\t\t                    cursor: pointer;\r\n");
      out.write("\t\t                }\r\n");
      out.write("\t\t                .jssorb05 div { background-position: -7px -7px; }\r\n");
      out.write("\t\t                .jssorb05 div:hover, .jssorb05 .av:hover { background-position: -37px -7px; }\r\n");
      out.write("\t\t                .jssorb05 .av { background-position: -67px -7px; }\r\n");
      out.write("\t\t                .jssorb05 .dn, .jssorb05 .dn:hover { background-position: -97px -7px; }\r\n");
      out.write("\t\t            </style>\r\n");
      out.write("\t\t            <!-- Slider navigator container -->\r\n");
      out.write("\t\t            <div u=\"navigator\" class=\"jssorb05\" style=\"bottom: 16px; right: 6px;\">\r\n");
      out.write("\t\t                <div u=\"prototype\"></div>\r\n");
      out.write("\t\t            </div>\r\n");
      out.write("\t\t          \r\n");
      out.write("\t\t            <style>\r\n");
      out.write("\t\t                .jssora11l, .jssora11r {\r\n");
      out.write("\t\t                    display: block;\r\n");
      out.write("\t\t                    position: absolute;\r\n");
      out.write("\t\t                    /* size of arrow element */\r\n");
      out.write("\t\t                    width: 37px;\r\n");
      out.write("\t\t                    height: 37px;\r\n");
      out.write("\t\t                    cursor: pointer;\r\n");
      out.write("\t\t                    background: url(../img/a11.png) no-repeat;\r\n");
      out.write("\t\t                    overflow: hidden;\r\n");
      out.write("\t\t                }\r\n");
      out.write("\t\t                .jssora11l { background-position: -11px -41px; }\r\n");
      out.write("\t\t                .jssora11r { background-position: -71px -41px; }\r\n");
      out.write("\t\t                .jssora11l:hover { background-position: -131px -41px; }\r\n");
      out.write("\t\t                .jssora11r:hover { background-position: -191px -41px; }\r\n");
      out.write("\t\t                .jssora11l.jssora11ldn { background-position: -251px -41px; }\r\n");
      out.write("\t\t                .jssora11r.jssora11rdn { background-position: -311px -41px; }\r\n");
      out.write("\t\t            </style>\r\n");
      out.write("\t\t            <!-- Arrow Left -->\r\n");
      out.write("\t\t            <span u=\"arrowleft\" class=\"jssora11l\" style=\"top: 123px; left: 1%;\">\r\n");
      out.write("\t\t            </span>\r\n");
      out.write("\t\t            <!-- Arrow Right -->\r\n");
      out.write("\t\t            <span u=\"arrowright\" class=\"jssora11r\" style=\"top: 123px; right: 1%;\">\r\n");
      out.write("\t\t            </span>\r\n");
      out.write("\t\t        </div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<script src=\"../js/jquery-1.9.1.min.js\"></script>\r\n");
      out.write("\t\t    <script src=\"../js/bootstrap.min.js\"></script>\r\n");
      out.write("\t\t    <script src=\"../js/docs.min.js\"></script>\r\n");
      out.write("\t\t    \r\n");
      out.write("\t\t    <script src=\"../js/ie10-viewport-bug-workaround.js\"></script>\r\n");
      out.write("\t\t    <script type=\"text/javascript\" src=\"../js/jssor.slider.mini.js\"></script>\r\n");
      out.write("\t\t    \r\n");
      out.write("\t\t    <script>\r\n");
      out.write("\t\t  //function to start the slider    \r\n");
      out.write("\t\t    jssor_slider1_starter = function (containerId) {\r\n");
      out.write("\t\t\t\t\t    \tvar options = {\r\n");
      out.write("\t\t\t\t\t                $AutoPlay: true,                                    //[Optional] Whether to auto play, to enable slideshow, this option must be set to true, default value is false\r\n");
      out.write("\t\t\t\t\t                $AutoPlaySteps: 1,                                  //[Optional] Steps to go for each navigation request (this options applys only when slideshow disabled), the default value is 1\r\n");
      out.write("\t\t\t\t\t                $AutoPlayInterval: 10000,                           //[Optional] Interval (in milliseconds) to go for next slide since the previous stopped if the slider is auto playing, default value is 3000\r\n");
      out.write("\t\t\t\t\t                $PauseOnHover: 1,                                   //[Optional] Whether to pause when mouse over if a slider is auto playing, 0 no pause, 1 pause for desktop, 2 pause for touch device, 3 pause for desktop and touch device, 4 freeze for desktop, 8 freeze for touch device, 12 freeze for desktop and touch device, default value is 1\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t                $ArrowKeyNavigation: true,   \t\t\t            //[Optional] Allows keyboard (arrow key) navigation or not, default value is false\r\n");
      out.write("\t\t\t\t\t                $SlideEasing: $JssorEasing$.$EaseOutQuint,          //[Optional] Specifies easing for right to left animation, default value is $JssorEasing$.$EaseOutQuad\r\n");
      out.write("\t\t\t\t\t                $SlideDuration: 800,                                //[Optional] Specifies default duration (swipe) for slide in milliseconds, default value is 500\r\n");
      out.write("\t\t\t\t\t                $MinDragOffsetToSlide: 20,                          //[Optional] Minimum drag offset to trigger slide , default value is 20\r\n");
      out.write("\t\t\t\t\t                //$SlideWidth: 600,                                 //[Optional] Width of every slide in pixels, default value is width of 'slides' container\r\n");
      out.write("\t\t\t\t\t                //$SlideHeight: 300,                                //[Optional] Height of every slide in pixels, default value is height of 'slides' container\r\n");
      out.write("\t\t\t\t\t                $SlideSpacing: 0, \t\t\t\t\t                //[Optional] Space between each slide in pixels, default value is 0\r\n");
      out.write("\t\t\t\t\t                $DisplayPieces: 1,                                  //[Optional] Number of pieces to display (the slideshow would be disabled if the value is set to greater than 1), the default value is 1\r\n");
      out.write("\t\t\t\t\t                $ParkingPosition: 0,                                //[Optional] The offset position to park slide (this options applys only when slideshow disabled), default value is 0.\r\n");
      out.write("\t\t\t\t\t                $UISearchMode: 1,                                   //[Optional] The way (0 parellel, 1 recursive, default value is 1) to search UI components (slides container, loading screen, navigator container, arrow navigator container, thumbnail navigator container etc).\r\n");
      out.write("\t\t\t\t\t                $PlayOrientation: 1,                                //[Optional] Orientation to play slide (for auto play, navigation), 1 horizental, 2 vertical, 5 horizental reverse, 6 vertical reverse, default value is 1\r\n");
      out.write("\t\t\t\t\t                $DragOrientation: 1,                                //[Optional] Orientation to drag slide, 0 no drag, 1 horizental, 2 vertical, 3 either, default value is 1 (Note that the $DragOrientation should be the same as $PlayOrientation when $DisplayPieces is greater than 1, or parking position is not 0)\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t                $ArrowNavigatorOptions: {                           //[Optional] Options to specify and enable arrow navigator or not\r\n");
      out.write("\t\t\t\t\t                    $Class: $JssorArrowNavigator$,                  //[Requried] Class to create arrow navigator instance\r\n");
      out.write("\t\t\t\t\t                    $ChanceToShow: 2,                               //[Required] 0 Never, 1 Mouse Over, 2 Always\r\n");
      out.write("\t\t\t\t\t                    $AutoCenter: 2,                                 //[Optional] Auto center arrows in parent container, 0 No, 1 Horizontal, 2 Vertical, 3 Both, default value is 0\r\n");
      out.write("\t\t\t\t\t                    $Steps: 1,                                      //[Optional] Steps to go for each navigation request, default value is 1\r\n");
      out.write("\t\t\t\t\t                    $Scale: false                                   //Scales bullets navigator or not while slider scale\r\n");
      out.write("\t\t\t\t\t                },\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t                $BulletNavigatorOptions: {                                //[Optional] Options to specify and enable navigator or not\r\n");
      out.write("\t\t\t\t\t                    $Class: $JssorBulletNavigator$,                       //[Required] Class to create navigator instance\r\n");
      out.write("\t\t\t\t\t                    $ChanceToShow: 2,                               //[Required] 0 Never, 1 Mouse Over, 2 Always\r\n");
      out.write("\t\t\t\t\t                    $AutoCenter: 1,                                 //[Optional] Auto center navigator in parent container, 0 None, 1 Horizontal, 2 Vertical, 3 Both, default value is 0\r\n");
      out.write("\t\t\t\t\t                    $Steps: 1,                                      //[Optional] Steps to go for each navigation request, default value is 1\r\n");
      out.write("\t\t\t\t\t                    $Lanes: 1,                                      //[Optional] Specify lanes to arrange items, default value is 1\r\n");
      out.write("\t\t\t\t\t                    $SpacingX: 12,                                   //[Optional] Horizontal space between each item in pixel, default value is 0\r\n");
      out.write("\t\t\t\t\t                    $SpacingY: 4,                                   //[Optional] Vertical space between each item in pixel, default value is 0\r\n");
      out.write("\t\t\t\t\t                    $Orientation: 1,                                //[Optional] The orientation of the navigator, 1 horizontal, 2 vertical, default value is 1\r\n");
      out.write("\t\t\t\t\t                    $Scale: false                                   //Scales bullets navigator or not while slider scale\r\n");
      out.write("\t\t\t\t\t                }\r\n");
      out.write("\t\t                        };\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t            $(\"#slider1_container\").css(\"display\", \"block\");\r\n");
      out.write("\t\t\t\t            var jssor_slider1 = new $JssorSlider$(\"slider1_container\", options);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t            function ScaleSlider() {\r\n");
      out.write("\t\t\t\t                var parentWidth = jssor_slider1.$Elmt.parentNode.clientWidth;\r\n");
      out.write("\t\t\t\t                if (parentWidth) {\r\n");
      out.write("\t\t\t\t                    jssor_slider1.$ScaleWidth(parentWidth - 30);\r\n");
      out.write("\t\t\t\t                }\r\n");
      out.write("\t\t\t\t                else\r\n");
      out.write("\t\t\t\t                    window.setTimeout(ScaleSlider, 30);\r\n");
      out.write("\t\t\t\t            }\r\n");
      out.write("\t\t\t\t            ScaleSlider();\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t            $(window).bind(\"load\", ScaleSlider);\r\n");
      out.write("\t\t\t\t            $(window).bind(\"resize\", ScaleSlider);\r\n");
      out.write("\t\t\t\t            $(window).bind(\"orientationchange\", ScaleSlider);\r\n");
      out.write("\t\t\t\t            \r\n");
      out.write("\t\t                    };\r\n");
      out.write("\t   \r\n");
      out.write("\t\t     $.ajax({\r\n");
      out.write("\t\t    \t url:\"/prj1/DispatchServlet?jspUrl=getImages\",\r\n");
      out.write("                 success:function(data){\r\n");
      out.write("                     var imgurls_str=data;\r\n");
      out.write("                     var imgurls=imgurls_str.split(';');\r\n");
      out.write("                     var imgHtmls='';\r\n");
      out.write("                     if(imgurls.length<=1){\r\n");
      out.write("                    \t jssor_slider1_starter('slider1_container');\r\n");
      out.write("                    \t return;\r\n");
      out.write("                     }\r\n");
      out.write("                     for(var i=0;i<imgurls.length;++i){\r\n");
      out.write("                    \t if(imgurls[i].length>=3){\r\n");
      out.write("                    \t\t imgHtmls+='<div><img u=\"image\" style=\"padding: 0 23%;width: auto!important;\" src2=\"../File/'+imgurls[i]+'\" /></div>'; \r\n");
      out.write("                    \t }\r\n");
      out.write("                     }\r\n");
      out.write("                     $(\"#slides\").html(imgHtmls);\r\n");
      out.write("                     jssor_slider1_starter('slider1_container');\r\n");
      out.write("                 }\r\n");
      out.write("             });\r\n");
      out.write("\t\t    </script>\r\n");
      out.write("\t\t</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
